version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: live
    open-pull-requests-limit: 10
    automerged_updates:
      - match:
        dependency_name: "development"
        update_type: "all"
      - match:
        dependency_name: "production"
        update_type: "all"
