version: 2
jobs:
  deps:
    docker:
      - image: circleci/node:11.14.0
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run:
          name: npm install
          command: |
            npm install
      - run:
          name: Download cc-test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./node_modules/cc-test-reporter
            chmod +x ./node_modules/cc-test-reporter
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}

  test:
    docker:
      - image: circleci/node:11.14.0
      - image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.2.0
        environment:
          'discovery.type': 'single-node'
          'bootstrap.system_call_filter': 'false'
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          command: |
            set +x
            npm install
            ./node_modules/.bin/wait-port -t 600000 localhost:9200
            ./node_modules/.bin/wait-port -t 600000 http://localhost:9200/_cluster/health?wait_for_status=green
            export ES_STARTED=1
            npm run cover:component
            ./node_modules/cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.component.json coverage/component/lcov.info
            npm run cover:system
            ./node_modules/cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.system.json coverage/system/lcov.info
      - persist_to_workspace:
          root: coverage
          paths:
            - codeclimate.component.json
            - codeclimate.system.json
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: test-results
      - save_cache:
          paths:
            - node_modules
            - target/gnaf
          key: dependencies-{{ checksum "package.json" }}

  test-geo:
    docker:
      - image: circleci/node:11.14.0
      - image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.2.0
        environment:
          'discovery.type': 'single-node'
          'bootstrap.system_call_filter': 'false'
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          command: |
            set +x
            npm install
            ./node_modules/.bin/wait-port -t 600000 localhost:9200
            ./node_modules/.bin/wait-port -t 600000 http://localhost:9200/_cluster/health?wait_for_status=green
            export ES_STARTED=1
            npm run cover:component:geo
            ./node_modules/cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.component-geo.json coverage/component-geo/lcov.info
            npm run cover:system:geo
            ./node_modules/cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.system-geo.json coverage/system-geo/lcov.info
      - persist_to_workspace:
          root: coverage
          paths:
            - codeclimate.component-geo.json
            - codeclimate.system-geo.json
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: test-results

  upload-coverage:
    docker:
      - image: circleci/node:11.14.0
    environment:
      CC_TEST_REPORTER_ID: 9511827b5c714ecf56f5af3bd77ecd90731821cd8c24b11edd55ed1e99575a1f
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - attach_workspace:
          at: coverage
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./node_modules/cc-test-reporter sum-coverage coverage/codeclimate.*.json -p 4 -o coverage/codeclimate.total.json
            ./node_modules/cc-test-reporter upload-coverage -i coverage/codeclimate.total.json

  build-and-release:
    docker:
      - image: circleci/node:11.14.0
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          command: |
            set +x
            npm install
            echo "//registry.npmjs.org/:_authToken=$NPM_AUTH" > ~/.npmrc
            npm pack
            npm run dopublish
            npm run build:docker
            npm run docker:push
            npm --unsafe-perm --no-git-tag-version version patch -m "Version bump to %s."
            git config user.email "tom@windyroad.com.au"
            git config user.name "Tom Howard"
            git add package.json
            git commit -m "Version bump. [skip ci]"
            git push origin HEAD:master && git push --tags

workflows:
  version: 2

  ci:
    jobs:
      - deps
      - test:
          requires:
            - deps
      - test-geo:
          requires:
            - deps
      - upload-coverage:
          requires:
            - test
            - test-geo
      - build-and-release:
          requires:
            - test
            - test-geo
          filters:
            branches:
              only:
                - master
