version: 2
jobs:
  build:
    # machine: true
    docker:
      - image: circleci/node:11.14.0
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            npm install
            # FAIL_FAST=" " npm run test
            echo "//registry.npmjs.org/:_authToken=$NPM_AUTH" > ~/.npmrc
            npm pack
            npm run dopublish
            npm run build:docker
            npm run docker:push
            npm --unsafe-perm --no-git-tag-version version patch -m "Version bump to %s."
            git config user.email "tom@windyroad.com.au"
            git config user.name "Tom Howard"
            git add package.json
            git commit -m "Version bump. [skip ci]"
            git push origin HEAD:master && git push --tags
      # - store_test_results:
      #     path: test-results
      # - store_artifacts:
      #     path: test-results
      #     destination: test-results
      - save_cache:
          paths:
            - node_modules
            - target/gnaf
          key: dependencies-{{ checksum "package.json" }}

workflows:
  version: 2

  ci:
    jobs:
      - build
