version: 2
jobs:
  build:
    machine: true
    # docker:
    #   - image: circleci/node:11.14.0
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      # - setup_remote_docker:
      #     docker_layer_caching: true
      - run:
          command: |
            npm install
            FAIL_FAST=" " npm run test
            npm pack
            npm run build:docker
            npm run docker:push
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: test-results
      - save_cache:
          paths:
            - node_modules
            - target/gnaf
          key: dependencies-{{ checksum "package.json" }}

workflows:
  version: 2

  ci:
    jobs:
      - build
