version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.14.0
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run:
          command: |
            npm install
            FAIL_FAST=" " npm run test
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - '*'
      - store_test_results:
          path: test-results

workflows:
  version: 2

  ci:
    jobs:
      - build
